-- Create Module table
create table if not exists "Module" (
  id bigint generated by default as identity primary key,
  "bootcampId" bigint not null references "Bootcamp"(id) on delete cascade,
  title text not null,
  "order" integer default 0,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Lesson table (Content)
create table if not exists "Lesson" (
  id bigint generated by default as identity primary key,
  "moduleId" bigint not null references "Module"(id) on delete cascade,
  title text not null,
  type text not null check (type in ('text', 'video', 'presentation')),
  content text, -- Stores HTML for text, URL for video/presentation
  "order" integer default 0,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (recommended)
alter table "Module" enable row level security;
alter table "Lesson" enable row level security;

-- Policy to allow full access (for now, similar to Bootcamp)
create policy "Enable all for authenticated users only" on "Module" for all using (true);
create policy "Enable all for authenticated users only" on "Lesson" for all using (true);
