-- Create Exam table
create table if not exists "Exam" (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  "timeLimitSeconds" integer default 300, -- 5 minutes default
  "createdAt" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Question table
create table if not exists "Question" (
  id bigint generated by default as identity primary key,
  "examId" bigint not null references "Exam"(id) on delete cascade,
  text text not null,
  "order" integer default 0
);

-- Create Option table
create table if not exists "Option" (
  id bigint generated by default as identity primary key,
  "questionId" bigint not null references "Question"(id) on delete cascade,
  text text not null,
  "isCorrect" boolean default false
);

-- Create ExamAttempt table (to track user submissions)
create table if not exists "ExamAttempt" (
  id bigint generated by default as identity primary key,
  "userId" uuid not null, -- Assuming Supabase Auth user id
  "examId" bigint not null references "Exam"(id) on delete cascade,
  "startedAt" timestamp with time zone default timezone('utc'::text, now()) not null,
  "finishedAt" timestamp with time zone,
  score integer
);

-- Create ExamResponse table (to store selected answers)
create table if not exists "ExamResponse" (
  id bigint generated by default as identity primary key,
  "attemptId" bigint not null references "ExamAttempt"(id) on delete cascade,
  "questionId" bigint not null references "Question"(id) on delete cascade,
  "optionId" bigint not null references "Option"(id) on delete cascade
);

-- RLS Policies (Basic)
alter table "Exam" enable row level security;
alter table "Question" enable row level security;
alter table "Option" enable row level security;
alter table "ExamAttempt" enable row level security;
alter table "ExamResponse" enable row level security;

create policy "Read access for all" on "Exam" for select using (true);
create policy "Read access for all" on "Question" for select using (true);
create policy "Read access for all" on "Option" for select using (true);

create policy "Users can insert their own attempts" on "ExamAttempt" for insert with check (auth.uid() = "userId");
create policy "Users can read their own attempts" on "ExamAttempt" for select using (auth.uid() = "userId");

create policy "Users can insert their own responses" on "ExamResponse" for insert 
with check (
    exists (
        select 1 from "ExamAttempt" 
        where id = "attemptId" and "userId" = auth.uid()
    )
);

-- Insert Dummy Data for Testing
with new_exam as (
  insert into "Exam" (title, description, "timeLimitSeconds")
  values ('Examen de Certificación React', 'Demuestra tus conocimientos en React, Hooks y Performance.', 300)
  returning id
),
new_q1 as (
  insert into "Question" ("examId", text, "order")
  select id, '¿Cuál es el hook utilizado para manejar efectos secundarios en React?', 1 from new_exam
  returning id
),
new_q2 as (
  insert into "Question" ("examId", text, "order")
  select id, '¿Qué método se utiliza para optimizar el renderizado de listas en React?', 2 from new_exam
  returning id
),
new_q3 as (
  insert into "Question" ("examId", text, "order")
  select id, '¿Cuál es la forma correcta de actualizar el estado basado en el estado anterior?', 3 from new_exam
  returning id
)
insert into "Option" ("questionId", text, "isCorrect")
values 
((select id from new_q1), 'useState', false),
((select id from new_q1), 'useEffect', true),
((select id from new_q1), 'useContext', false),
((select id from new_q1), 'useReducer', false),

((select id from new_q2), 'key props', true),
((select id from new_q2), 'index', false),
((select id from new_q2), 'random id', false),
((select id from new_q2), 'memo', false),

((select id from new_q3), 'setState(newState)', false),
((select id from new_q3), 'setState(prev => prev + 1)', true),
((select id from new_q3), 'state = newState', false),
((select id from new_q3), 'forceUpdate()', false);
