-- Create BootcampStudent table
create table if not exists "BootcampStudent" (
  id bigint generated by default as identity primary key,
  "bootcampId" bigint not null references "Bootcamp"(id) on delete cascade,
  email text not null,
  status text not null default 'invited' check (status in ('invited', 'active', 'completed')),
  "invitedAt" timestamp with time zone default timezone('utc'::text, now()) not null,
  "joinedAt" timestamp with time zone,
  "userId" uuid, -- Allow mapping to Auth users
  unique("bootcampId", email)
);

-- Enable RLS
alter table "BootcampStudent" enable row level security;

-- Policies (Simplified for now)
create policy "allow_all_auth" on "BootcampStudent" for all using (true);
