-- Create LessonCompletion table
create table if not exists "LessonCompletion" (
  id bigint generated by default as identity primary key,
  "studentId" bigint not null references "BootcampStudent"(id) on delete cascade,
  "lessonId" bigint not null references "Lesson"(id) on delete cascade,
  "completedAt" timestamp with time zone default timezone('utc'::text, now()) not null,
  unique("studentId", "lessonId")
);

-- Enable RLS
alter table "LessonCompletion" enable row level security;

-- Policy (Simplified)
create policy "allow_all_auth" on "LessonCompletion" for all using (true);
