-- Create Certificate table for custom certificate templates
create table if not exists "Certificate" (
  id bigint generated by default as identity primary key,
  "bootcampId" bigint not null references "Bootcamp"(id) on delete cascade,
  title text not null,
  "backgroundImageUrl" text, -- URL of the uploaded background image
  "textColor" text default '#000000',
  "titleFontSize" integer default 24,
  "nameFontSize" integer default 32,
  "programFontSize" integer default 20,
  "dateFontSize" integer default 14,
  "namePositionY" integer default 50, -- Percentage from top
  "programPositionY" integer default 60,
  "datePositionY" integer default 75,
  "showInstructorSignature" boolean default true,
  "showDirectorSignature" boolean default true,
  "instructorName" text,
  "directorName" text,
  "instructorSignatureUrl" text, -- URL of the instructor's digitized signature PNG
  "directorSignatureUrl" text, -- URL of the director's digitized signature PNG
  "isActive" boolean default false, -- Only one active certificate per bootcamp
  "createdAt" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updatedAt" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create unique index to ensure only one active certificate per bootcamp
create unique index "Certificate_bootcamp_active_unique" 
on "Certificate" ("bootcampId") 
where "isActive" = true;

-- Enable RLS
alter table "Certificate" enable row level security;

-- Policy to allow full access for authenticated users
create policy "Enable all for authenticated users only" on "Certificate" for all using (true);

-- Add trigger for updatedAt
create or replace function update_certificate_updated_at()
returns trigger as $$
begin
  new."updatedAt" = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

create trigger certificate_updated_at
  before update on "Certificate"
  for each row
  execute function update_certificate_updated_at();
