-- Create Masterclass table
create table if not exists "Masterclass" (
  id bigint generated by default as identity primary key,
  "bootcampId" bigint not null references "Bootcamp"(id) on delete cascade unique,
  "videoUrl" text,
  description text,
  materials jsonb default '[]'::jsonb,
  "createdAt" timestamp with time zone default timezone('utc'::text, now()) not null,
  "updatedAt" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table "Masterclass" enable row level security;

-- Policy to allow read access to authenticated users
create policy "Allow read access for authenticated users" on "Masterclass"
  for select using (true);

-- Policy to allow edit for admin and teachers
create policy "Allow edit for admin and teachers" on "Masterclass"
  for all using (
    exists (
      select 1 from public."UserRole"
      where public."UserRole".id = auth.uid()
      and public."UserRole".role in ('docente', 'superadmin')
    )
  );
